version: '3.9'

services:
  postgres: 
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command: [
      "-path=/migrations",
      "-database=postgres://postgres:postgres%40123@postgres:5432/todo_db?sslmode=disable",
      "up"
    ]
    
  app:
    build: .
    container_name: golang_app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

volumes:
  postgres_data: